- name: cri-o and kuber tools
  hosts: myhosts
  remote_user: root

  tasks:
    - name: Add the dummy module
      modprobe:
        name: "{{  item  }}"
        state: present
      with_items:
        - br_netfilter
        - bridge

    - name: Disable SWAP in fstab
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

    - name: Configure sysctl parameters for K8S
      lineinfile:
        path: /etc/sysctl.conf
        line: "{{ item }}"
      with_items:
        - "net.bridge.bridge-nf-call-iptables  = 1"
        - "net.ipv4.ip_forward                 = 1"
        - "net.bridge.bridge-nf-call-ip6tables = 1"
          
    - name: Set ip_forward
      sysctl:
        name: net.ipv4.ip_forward
        value: 1

    - name: Install crio
      include_role:
        name: crio

      vars:
        version: 1.29

    - name: Install Kuber's tool
      include_role:
        name: kubers-tool 
